collections:
  posts:
    output: true
    permalink: /:collection/:name

gems:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
  enabled: 'all'
  layout: 'post-list'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Blog | Leah von Ahlburg Collection
author:
  name: Leah von Ahlburg
  email: info@leahvonahlburg.com
social:
  name: Leah von Ahlburg
  links:
    - blog.leahvonahlburg.com
